配信ネタ

Connpassでイベント設定

*目的
ブログじゃ書ききれないことをとりあえずアウトプットする場
1人でどのくらい話せるか試したい
毎週水曜/木曜
夜9時くらいから1時間
細かいことは走りながら決める

** ラジオを始めた理由
*** 技術の話するのが好き
*** ラジオも好き
小学生の頃ラジオめっちゃ買ってた。短波ラジオ持ってる。
ラジオの話はsizu.meに色々書いている。
** ハム4の話
中学の頃に取った。
登山の連絡用だったけど、結局その後から家族で登山に行けてない。 
** 日報の話
唐突に始めた。どうぜ三日坊主に終わると思ったのだけど、いまだに続いていて奇跡に近い。
** RSS版Zenn
良い技術記事をキュレーションする仕組みを作りたい。
読まれないから...で記事を書くのをやめてしまう状況を無くしていきたい。
** vim-morg
org-modeに感動したのでVimでそのエッセンスを再現できないか試している。
実装はremarkを使っている。

現状babelとtangle、outlineを検索できるddu soruceが実装されている。
** VimConf
** Gleam
*** use
コールバックを展開して記述できる構文。Gleamの本懐はこれにあると思っている。
構文の由来としては、公式の情報こそないもののkokaのwith構文が由来だと考えている。
** Emacs
** 最近気になってる言語
*** koka
*** hy
最近v1に到達した。
LispでFastAPIしたい!
** キュレーション 
基準としては魂が震えるかどうかで決めている。
** アイマス
*** 始めた理由
U149見て始めた。
*** 学マス前夜
周囲の反応としては「また新しいブランド作るの？」「俺達の学マスはこれだ!」みたいなのがあった気がする。
高校と聞いてU149クラスタは残念がっていた...が、倉本千奈ちゃんが登場してから一変したのを感じる。

「Qualiartsってどこ？」という声もあったけど、CAにいることが分かってからかなり評価が変わったと思う。

始めは否定的な意見も多かったけど、なんだかんだみんな毎週の生放送見て楽しんできた気がする。
6万ポリゴンと聞いた時はびっくりした。
*** ラ！

*** シャニマス
*** 放クラ
**** Many screens
じゅりんぜがひたすらに尊い。
樹里ちゃんがちょこ先のお母さんを知っているっていう背景を考えただけでご飯3杯はいける。

古典落語「死神」にまつわる話なので、落語経験者としても楽しめるものだった。
*** ミーム
** 月曜が近いやつ
** 嘘シャニマス聖地
それっぽい写真を撮ってくるの好き。純粋に写真が上手い。
良識ある方という印象。
** エビ揉め
なんで流行ったんだ...
発端はシャニマスだけど、流行った原因は学マス派生。clumsy trickは良いぞ。
** BlueSky
** Nostr
** Vim

***使い始めたきっかけ
それしかなかった。
** 編み物
鉤針棒針両方できる。帽子とか作れる。
自作した帽子を鞍馬寺に置いてきてしまった。
** 登山
*** 八方尾根
始めての登山？
グライダーやってる人が沢山いたのが印象的だった。
山頂で食べたシーフードが美味かった。
*** 北ア
**** 上高地
何回か行った。
始めての山は八方尾根か上高地だった。
**** 涸沢
行った日が初雪でめちゃくちゃ寒かった。
**** 双六
ただただ長かった記憶がある。
星空がすごく綺麗だった。
** スノボ
一日で習得できた。 
来年はトリックを習得したい。
** ブレイブボード
ブレイクボードではない。
** ボルダリング
一度ジムに行ったことがあったけど、身長制限で門前払いされたので再チャレンジしたい。
** 一輪車
そこそこ乗れる。またやってみたい。
